### ISSUE TITLE
Clean up README.md file

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/date_all_day#2]
The README.md file for this project is not properly formatted.  Sometimes this can happen when projects are ported over from Drupal, since there wasn't a lot of direction on formatting of Drupal's README.txt files.

Please refer to our [contributor guidelines](https://github.com/backdrop-ops/contrib) for an [example README.md file](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) that you can copy. The main problem is the HTML formatting, that should be removed.  Markdown files (ending in .md) have [their own formatting](https://help.github.com/articles/markdown-basics) similar to what we use here on GitHub :)

It is especially important to keep the readme files clean for Backdrop projects because that is what is used for the project page on backdropcms.org.  Take a look at the page for this project to see the problem: https://backdropcms.org/project/date_all_day

**Comment by Graham-72** [comment]
I think this was fixed some time ago. It seems OK in the latest release.
