### ISSUE TITLE
Undefined index: $settings['display_all_day']

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/date_all_day#3]
On the field settings page:

`Notice: Undefined index: display_all_day in date_all_day_date_field_widget_settings_form_alter() (line 440 of /home/siteroot/modules/date_all_day/date_all_day.module).`

I'll submit a PR to fix this shortly.

**Comment by olafgrabienski** [comment]
I can confirm the issue. Additionally to the notice mentioned above I see a `Theme hook "" not found.` warning. (Not able to test the PR at the moment but I hope to come back to it.)

**Comment by Graham-72** [comment]
Thanks @laryn for this PR. My apologies for taking so long to confirm the merge.
